// Code generated by "stringer -type=Capability"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CanAutoDNSSEC-0]
	_ = x[CanConcur-1]
	_ = x[CanGetZones-2]
	_ = x[CanOnlyDiff1Features-3]
	_ = x[CanUseAKAMAICDN-4]
	_ = x[CanUseAlias-5]
	_ = x[CanUseAzureAlias-6]
	_ = x[CanUseCAA-7]
	_ = x[CanUseDHCID-8]
	_ = x[CanUseDNAME-9]
	_ = x[CanUseDS-10]
	_ = x[CanUseDSForChildren-11]
	_ = x[CanUseHTTPS-12]
	_ = x[CanUseLOC-13]
	_ = x[CanUseScopedMultipleCNAMEs-14]
	_ = x[CanUseNAPTR-15]
	_ = x[CanUsePTR-16]
	_ = x[CanUseRoute53Alias-17]
	_ = x[CanUseRP-18]
	_ = x[CanUseSMIMEA-19]
	_ = x[CanUseSOA-20]
	_ = x[CanUseSRV-21]
	_ = x[CanUseSSHFP-22]
	_ = x[CanUseSVCB-23]
	_ = x[CanUseTLSA-24]
	_ = x[CanUseDNSKEY-25]
	_ = x[CanUseOPENPGPKEY-26]
	_ = x[DocCreateDomains-27]
	_ = x[DocDualHost-28]
	_ = x[DocOfficiallySupported-29]
	_ = x[CanUseAKAMAITLC-30]
}

const _Capability_name = "CanAutoDNSSECCanConcurCanGetZonesCanOnlyDiff1FeaturesCanUseAKAMAICDNCanUseAliasCanUseAzureAliasCanUseCAACanUseDHCIDCanUseDNAMECanUseDSCanUseDSForChildrenCanUseHTTPSCanUseLOCCanUseScopedMultipleCNAMEsCanUseNAPTRCanUsePTRCanUseRoute53AliasCanUseRPCanUseSMIMEACanUseSOACanUseSRVCanUseSSHFPCanUseSVCBCanUseTLSACanUseDNSKEYCanUseOPENPGPKEYDocCreateDomainsDocDualHostDocOfficiallySupportedCanUseAKAMAITLC"

var _Capability_index = [...]uint16{0, 13, 22, 33, 53, 68, 79, 95, 104, 115, 126, 134, 153, 164, 173, 199, 210, 219, 237, 245, 257, 266, 275, 286, 296, 306, 318, 334, 350, 361, 383, 398}

func (i Capability) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Capability_index)-1 {
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Capability_name[_Capability_index[idx]:_Capability_index[idx+1]]
}
